PieVerse.Web/Controllers/PieverseController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using PieVerse.BLL.Interfaces;
using PieVerse.DomainModel.Entities;
using PieVerse.Web.Attributes;
using PieVerse.Web.Models;
using WebGrease.Css.Extensions;

namespace PieVerse.Web.Controllers
{
    [PieverseAuthorize]
    public class PieverseController : Controller
    {
        private readonly IService _service;

        public PieverseController(IService service)
        {
            _service = service;
        }

        [ActionName("feed")]
        public ActionResult GetFeed()
        {
            ViewBag.NewActive = "active";
            ViewBag.PopularActive = "";
            IEnumerable<Pieverse> pieverses = _service.PieverseService.Get().OrderByDescending(p => p.AddingTime).ToList();
            return View(pieverses.Select(Mapper.Map<PieverseViewModel>));
        }

        [HttpGet]
        [ActionName("add")]
        public ActionResult Add()
        {
            FirstLine line = _service.FirstLineService.GetRandomFirstLine();
            IEnumerable<FirstLineViewModel> lines = _service.FirstLineService.Get().Select(Mapper.Map<FirstLineViewModel>);
            return View(new PieverseViewModel() { FirstLine = Mapper.Map<FirstLineViewModel>(line), AllLines = lines });
        }

        [HttpPost]
        [ActionName("AddPieverse")]
        public ActionResult Add(PieverseViewModel model)
        {
            var lines = _service.FirstLineService.Get().Select(Mapper.Map<FirstLineViewModel>);
            model.AllLines = lines;
            if (ModelState.IsValid)
            {
                _service.PieverseService.Add(Mapper.Map<Pieverse>(model), User.Identity.Name);
                return Content("Пирожок успешно добавлен!");
            }
            return PartialView("_addPieverse", model);
        }

        [HttpPost]
        [ActionName("AddFirstline")]
        public ActionResult Add(FirstLineViewModel model)
        {
            if (ModelState.IsValid)
            {
                _service.FirstLineService.Add(Mapper.Map<FirstLine>(model), User.Identity.Name);
                return Content("Строка успешно добавлена!");
            }
            return PartialView("_addFirstLine", model);
        }

        public ActionResult Sort(string sorting)
        {
            IEnumerable<Pieverse> pieverses = _service.PieverseService.Get().ToList();
            switch (sorting)
            {
                case "new":
                    pieverses = pieverses.OrderByDescending(p => p.AddingTime);
                    ViewBag.NewActive = "active";
                    ViewBag.PopularActive = "";
                    return View("feed", pieverses.Select(Mapper.Map<PieverseViewModel>));
                case "popular":
                    ViewBag.NewActive = "";
                    ViewBag.PopularActive = "active";
                    pieverses = pieverses.OrderByDescending(p => p.Likes.Count);
                    return View("feed", pieverses.Select(Mapper.Map<PieverseViewModel>));
            }
            return RedirectToAction("feed");
        }

        public PartialViewResult RefreshLine()
        {
            FirstLine line = _service.FirstLineService.GetRandomFirstLine();
            return PartialView("_FirstLine", new FirstLineViewModel() { Text = line.Text, Id = line.Id });
        }

        public ActionResult Delete(int id)
        {
            _service.LikeService.DeleteLikesOf(pieverseId: id);
            _service.PieverseService.Delete(id);
            return RedirectToAction("feed");
        }

        public ActionResult Like(int id)
        {
            var newLikesCount = _service.LikeService.Like(pieverseId: id, userName: User.Identity.Name);
            return Content(newLikesCount.ToString());
        }
    }
}

PieVerse.Web/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link href='https://fonts.googleapis.com/css?family=Amatic+SC' rel='stylesheet' type='text/css' />
    <link href='https://fonts.googleapis.com/css?family=Play:400,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <meta charset="utf-8" />
    <title>Пирожковая</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
        (c) 2015 PieVerse
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

PieVerse.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="@User.IsInRole("Admin")? ''admin' : ''">
<head>
    <link href='https://fonts.googleapis.com/css?family=Amatic+SC' rel='stylesheet' type='text/css' />
    <link href='https://fonts.googleapis.com/css?family=Play:400,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <meta charset="utf-8" />
    <title>Пирожковая</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    
    @Scripts.Render("~/bundles/jquery")
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    @Scripts.Render("~/Scripts/Redirect.js")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</head>
<body>

    <header>
        <h1 class="logo">PieVerse</h1><br/>
        <ul class="menu">
            <li class="@ViewBag.ReadStyle">@Html.ActionLink("Читать", "feed", "Pieverse")</li>
            <li class="@ViewBag.WriteStyle">@Html.ActionLink("Писать", "add", "Pieverse")</li>
        </ul>
    </header>

    <main>
        @RenderBody()
    </main>
    <footer>
        (c) 2015 PieVerse
    </footer>
    
    <script>
    
    $(".line-menu a").click( function (event) { 
        event.preventDefault();
        $("#firstLine").html($(this).html());
        $("#FirstLine_Id").val($(this).attr("id"));
        $("#FirstLine_Body").val($(this).html());
        $("html, body").animate({ scrollTop: 0 }, "fast");
    });

    $(".like").click(function() {$(this).toggleClass("active");});
    
    </script>
    
</body>
</html>